name: CMake Build (Windows x86-64)

on:
  push:
    branches:
      - MelonRipper

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
          msystem: MINGW64
          update: true

    - name: Install dependencies
      run: pacman -Sq --noconfirm git pkgconf mingw-w64-x86_64-{cmake,SDL2,qt5-static,libslirp,libarchive,toolchain}

    - name: Configure
      working-directory: ${{runner.workspace}}
      run: cmake -B build $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_STATIC=ON -DCMAKE_PREFIX_PATH=C:/tools/msys64/mingw64/qt5-static

    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .

    - name: Zip
      shell: cmd
      working-directory: ${{runner.workspace}}/build
      run: |
        mv melonDS.exe melonDS-MelonRipper.exe
        7z a melonDS-MelonRipper.zip melonDS-MelonRipper.exe

    - name: Tag
      working-directory: ${{github.workspace}}
      run: |
        git tag --force MelonRipperBuild ${{ github.sha }}
        git push --force origin MelonRipperBuild

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: MelonRipperBuild
        artifacts: ${{runner.workspace}}/build/melonDS-MelonRipper.zip
        allowUpdates: true
        omitBodyDuringUpdate: true
        token: ${{ secrets.GITHUB_TOKEN }}
