name: CMake Build (Windows x86-64)

on:
  push:
    branches:
      - MelonRipper

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
          msystem: MINGW64
          update: true

    - name: Install dependencies
      run: pacman -Sq --noconfirm git make mingw-w64-x86_64-{cmake,mesa,SDL2,qt5-static,libslirp,libarchive,libepoxy,toolchain}

    - name: Create build environment
      working-directory: ${{runner.workspace}}
      run: mkdir build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G 'MSYS Makefiles' -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_STATIC=ON -DCMAKE_PREFIX_PATH=C:/tools/msys64/mingw64/qt5-static

    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: make -j$(nproc --all)

    - name: Zip
      shell: cmd
      working-directory: ${{runner.workspace}}/build
      run: |
        mv melonDS.exe melonDS+MelonRipper.exe
        7z a melonDS+MelonRipper.zip melonDS+MelonRipper.exe

    - name: Tag
      working-directory: ${{github.workspace}}
      run: |
        git tag --force MelonRipperBuild ${{ github.sha }}
        git push --force origin MelonRipperBuild

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{runner.workspace}}/build/melonDS+MelonRipper.zip
        body: >
          Automated build of the latest MelonRipper branch
          for use with https://github.com/scurest/MelonRipper.
          Windows 64-bit EXE.


          NOTE:
          This is *not* an official melonDS build.
          It's based on an older melonDS release,
          so it may have bugs the latest melonDS has fixed,
          be incompatible with the latest melonDS's savestates,
          etc.
        tag: MelonRipperBuild
        token: ${{ secrets.GITHUB_TOKEN }}
